stages:
  - test
  - sonar

test:
  stage: test
  image: trion/ng-cli-karma:14.2.1
  script:
    - npm ci --force
    - ng build
    - ng test --code-coverage --watch=false --browsers=Chrome

sonar:
  stage: sonar
  image: trion/ng-cli:14.2.1
#  only:
#    - develop
  script:
    - npm ci --force
    - npm run sonar -- -Dsonar.host.url=${SONAR_HOST} -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.projectName=${SONAR_PROJECT_NAME} -Dsonar.branch.name=develop -Dsonar.login=${SONAR_LOGIN_TOKEN}
