stages:
  - test
  - sonar
  - build

test:
  stage: test
  image: trion/ng-cli-karma:15.2.10
  script:
    - npm ci --force
    - ng build
    - ng test --code-coverage --watch=false --browsers=Chrome
  coverage: '/Lines.*?(\d+(?:\.\d+)?)%/'
  artifacts:
    paths:
      - coverage/

sonar:
  stage: sonar
  image: trion/ng-cli:15.2.10
  only:
    - develop
  script:
    - npm ci --force
    - npm run sonar -- -Dsonar.host.url=${SONAR_HOST} -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.projectName=${SONAR_PROJECT_NAME} -Dsonar.branch.name=develop -Dsonar.login=${SONAR_LOGIN_TOKEN}

build_and_push_latest_image:
  stage: build
  only:
    - develop
  variables:
    IMAGE_TAG: "latest"
  script:
    - |
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REPOSITORY
      docker build -t $DOCKER_REPOSITORY_LOCAL:$IMAGE_TAG .
      docker push $DOCKER_REPOSITORY_LOCAL:$IMAGE_TAG
      docker logout $DOCKER_REPOSITORY