name: Run build and test

on:
  push:
    branches:
      - '*'

jobs:
  run-build-and-test:
    runs-on: ubuntu-22.04
    container:
      image: docker://trion/ng-cli-karma:14.2.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --force

      - name: Build
        run: ng build

      - name: Execute tests and code coverage
        run: ng test --code-coverage --watch=false --browsers=Chrome
