on: push
jobs:
  git-sync:
    runs-on: self-hosted
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: 'git@github.com:nmaas-platform/nmaas-portal.git'
          source_branch: 'refs/remotes/source/*'
          destination_repo: 'git@gitlab.geant.org:nmaas/nmaas-portal.git'
          destination_branch: 'refs/heads/*'
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }}
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}